### ISSUE TITLE
display not giving value

### ISSUE THREAD

**Issue by saurabhka9** [Andoramb/OHMARDNEX#2]
as per your direction I have 
1) flash the Arduino nano with your code.
2) flash the .tft file to Nextion NX4832K035_011.
3) open OHMARDNEX.exe to run it.
but nextion display not showing value  like RAM, CPU uses etc.
any suggestion?

**Comment by Andoramb** [comment]
Do you run it with admin rights?

**Comment by saurabhka9** [comment]
Run with admin right but not displaying value.
when I flash .tft file in Nextion it show version is too low, so open .hmi file in Nextion editor window
and compile  it again and make .tft file with choosing option NX4832K035. than copy .tft file a new 32Gb flash card with FAT32 formatted.
nextion pin red=+5v, black=gnd, Yellow=Rx, blue=Tx
so **Yellow(rx) connected to 11 pin
  Blue(tx) to 12 pin of Arduino** 
the connection with Arduino  
i have attach some screenshot for you. i don't understand what is problem or i mistake something
![20220222_102337](https://user-images.githubusercontent.com/100137488/155066315-1288b460-fcfb-4210-9b15-92041b12c7fa.jpg)
![20220222_102102](https://user-images.githubusercontent.com/100137488/155066364-4d2c421f-0de5-4d24-9cb5-b011b0d7ac3d.jpg)
![20220222_102111](https://user-images.githubusercontent.com/100137488/155066380-b5a50252-f51a-4acc-a807-2593ace1142b.jpg)
![20220222_102142](https://user-images.githubusercontent.com/100137488/155066802-3d3553e4-ea20-4703-b7d0-52b203c27721.jpg)
.

**Comment by Andoramb** [comment]
Let's start analyzing the situation, take it step-by-step:

1. Is the COM port the same for arduino and the app? Baud rate should match (or set it to 115200)
2. Try to manually change the COM port to a different one in Device Manager
3. Not sure about the pin output, but switch Tx with Rx?
4. You can also try the communication with the FTDI device (the one you used to flash the display)
4.1.  of course check the pins to be connected correctly, then set the corresponding COM port in the windows app
4.2. because the arduino is just a Serial communication interface/gateway for the display in order not to use the FTDI
5. Try to send commands to the nextion display via the app (like _sleep_)
6. You can also debug in the nextion windows app, but that's a bit more complicated (create virtual COM port and send the data there)

The pictures look ok :)

**Comment by Andoramb** [comment]
Closed due to inactivity
